### PR TITLE
Content-Length and Transfer-Encoding handling

### PR DESCRIPTION
**Pull request by hvesalai**
Code-review changes with intent to make the code one step closer to what the specification mandates.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
See my comment for commit 3892cda for the details but in general, :+1:. 

By chance have you looked into what effect (if any) this will have on http4s proper? I doubt it will be significant but it might be worth double checking. I'll try to take a peak in the near future but probably not tonight.

**Comment by hvesalai** [comment]
@bryce-anderson can you look at the test log. There are some exceptions in it although all tests should pass now. Are they expected?

**Comment by hvesalai** [comment]
Ref to http4s proper. I think it is using the parser, so the content-length parsing changes should have an effect.

**Comment by bryce-anderson** [comment]
@hvesalai, I believe those exceptions are expected. I suppose they could probably be replaced by a more consistent exception.

**Comment by bryce-anderson** [comment]
@hvesalai, thanks for the PR!

**Pull request merged**
