### PR TITLE
Build for Scala 2.12.x

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by bryce-anderson** [comment]
Yeah! Just waiting for http4s-websocket to sync to central and turn the travis build green, but I think this is ready!

**Comment by bryce-anderson** [comment]
Just realized we should change the travis.yml file, too.

**Comment by rossabaker** [comment]
The [directory](https://repo1.maven.org/maven2/org/http4s/http4s-websocket_2.10/0.1.5) is there.  It shows the pom.  But [the pom](https://repo1.maven.org/maven2/org/http4s/http4s-websocket_2.10/0.1.5/http4s-websocket_2.10-0.1.5.pom) 404s. 😕

**Comment by bryce-anderson** [comment]
That happened to me last week. Took about a day to finally sync.

**Comment by rossabaker** [comment]
https://issues.sonatype.org/browse/MVNCENTRAL-1348

**Comment by bryce-anderson** [comment]
Yeah! It works. Merging.

**Pull request merged**
