### PR TITLE
Drop alpn vulnerable dependency

### PR DESCRIPTION
**Pull request by joan38**
Attempt to solve https://github.com/http4s/blaze/issues/235

### CODE REVIEW

**Comment by joan38** [comment]
```
[warn] blaze-http >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "org.eclipse.jetty" % "jetty-alpn-openjdk8-client" % "9.4.12.v20180830"
[info] Compiling 8 Scala sources to /home/travis/build/http4s/blaze/examples/target/scala-2.12/classes ...
[info] Done compiling.
[info] blaze-examples >>> The project has no unused dependencies declared in libraryDependencies. Good job!
[error] (blaze-http / unusedCompileDependenciesTest) Failing the build because unused dependencies were found
```
This is not true. If the lib is remove it won't compile.
What can we do?

**Comment by rossabaker** [comment]
jetty-alpn-openjdk8-client is not directly used, which is the reason for this error.  That's intended to be a runtime dependency at application level, not a library dependency.

The reason that removing jetty-alpn-openjdk8-client fails to compile is that it transtively pulls in alpn-api, which _is_ a compile time dependency.

I am still unclear whether there is a vulnerability in the API, as opposed to the implementation.  See comment on #235.

**Comment by rossabaker** [comment]
What dependency checker is blacklisting this?  My question remains: is the vulnerability in the _API_ or in the _implementation_?  The CVEs refer to older versions of Jetty.  There is no newer version of this API.  As far as I can tell, the vulnerability is in older versions of the implementation.

**Comment by joan38** [comment]
sbt-dependency-check, look at the code I added the plugin to try out and it seems that `Provided` is not making him happy.
I see what you mean I don't know why this is flagged like this.

**Comment by joan38** [comment]
I found a project excluding it:
https://github.com/Opetushallitus/koski/blob/master/owasp-dependency-check-suppressions.xml

**Comment by joan38** [comment]
Alright I think we can close this. The solution is to add this false positive exception in that XML file.

**Pull request closed without merging**
