### PR TITLE
Trace time spent in various SSLStage methods

### PR DESCRIPTION
**Pull request by rossabaker**
Most of this diff is regrettable reindentation.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
Looks good to me. I know this is an effort to help @etorreborre debug his client latency issues, which is good enough, but have we had any other reports of high latency under similarly suspicious conditions?

**Comment by rossabaker** [comment]
He's the first to report it.  I'd still be interested to see a profiler, and whether we're running into contention on the handshake queue.

This logging shouldn't cost anything but System.nanoTime and logger.isTraceEnabled.

**Comment by rossabaker** [comment]
Is there any reason we trace by default?  That seems to make Travis cranky.

**Comment by bryce-anderson** [comment]
No, please feel free to change the log level. Haven't checked, but I vaguely remember this being changed on master.

**Pull request merged**
