### PR TITLE
Add workaround for lightbend/mima#422

### PR DESCRIPTION
**Pull request by aeons**

### CODE REVIEW

**Comment by rossabaker** [comment]
Still seems to be failing.

**Comment by plokhotnyuk** [comment]
shouldn't it be defined in `project/plugins.sbt`?

**Comment by aeons** [comment]
Yeah, that probably makes sense.

**Comment by plokhotnyuk** [comment]
@aeons [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/project/plugins.sbt#L2) is a more concise line that works for me as a W/A for that problem.

**Comment by aeons** [comment]
Hah, yeah I was wondering why he would use the long-form of the resolver, but I thought that was part of the workaround.

**Comment by aeons** [comment]
Ah, and it seems the entire issue is resolved now anyway :D

**Pull request closed without merging**
